kitty_mod ctrl+shift

map kitty_mod+enter new_tab
map kitty_mod+w close_tab
map kitty_mod+l next_tab
map kitty_mod+h previous_tab
map kitty_mod+w close_tab
map kitty_mod+0 set_tab_title
map kitty_mod+y open_url_with_hints

