include current-theme.conf
include binds.conf

# BEGIN_KITTY_FONTS
font_family      family="Hack Nerd Font"
bold_font        "Hack Nerd Font"
italic_font      "Hack Nerd Font"
bold_italic_font "Hack Nerd Font"
font_size        16.0

# BEGIN_KITTY_THEME
wayland_title_bar_color system

# TAB_SETTINGS
tab_bar_edge top
tab_bar_style powerline
tab_powerline_style round

# STYLING
adjust_line_height 4
adjust_column_width 1
disable_ligatures never
cursor_shape block
cursor_blink_interal 0.8
background_opacity 0.6
background_blur 0
transparent_background_colors
background_image none

# SCROLLBACK
scrollback_lines 5000
scrollback_pager_history_size 10

# PERFORMANCE
sync_to_monitor yes
repaint_delay 10

# Window layout
remember_window_size  no
initial_window_width  800
initial_window_height 400

# SHELL
shell /usr/bin/zsh
shell_integration enabled

# MISC
open_url_with default
